### ISSUE TITLE
Markdown inconsistencies.

### ISSUE THREAD

**Issue by vigliensoni** [mouseandthebillionaire/_lestTenHorizonsCry#1]
There appear to be inconsistencies between Obsidian and Github markdowns. Bullet points are not recognized, and references to other notes in the vault are not linked.

https://github.com/mouseandthebillionaire/_lestTenHorizonsCry/blob/5de4edba8a0aa6d34805215babaccf145969d441/docs/Process/Journal.md?plain=1#L31C1-L34C24

https://github.com/mouseandthebillionaire/_lestTenHorizonsCry/blob/5de4edba8a0aa6d34805215babaccf145969d441/docs/Process/Journal.md?plain=1#L38

**Comment by mouseandthebillionaire** [comment]
Fixed!
